from ....core import Item as Item, Transforms as Transforms

class DbEnumName(Transforms.Safe[Item.Key, str]):
    postfix: str
    def transform(self, i: Item.Key) -> str: ...
    def __invert__(self) -> ItemKey: ...

class ItemKey(Transforms.Safe[str, Item.Key]):
    postfix: str
    def transform(self, i: str) -> Item.Key: ...
    def __invert__(self) -> DbEnumName: ...
